### ISSUE TITLE
Configuration messing with markdown

### ISSUE THREAD

**Issue by ctfpwner** [eyalz800/vimrc#7]
Hi. What's the vim configuration that messes all input text like:
```
**blah**
```
What happens when I enter `**` it's basically my chars are visually hidden while they are still there (it's like markdown is being rendered). This is pretty annoying. Any idea how to disable this?

Thank you.

**Comment by eyalz800** [comment]
@ctfpwner I'm away from my laptop right now, I never saw this, but it sounds like the conceal feature in vim, need to find which plugin is setting this for you and disable it

**Comment by ctfpwner** [comment]
Right! Found it. It's `indentLine`. If I add `let g:indentLine_setConceal = 0` to my `.vimrc` the problem goes away since the `indentLine` settings won't overwrite the default settings.
Thank you.

**Comment by eyalz800** [comment]
@ctfpwner you should read this thread then https://vi.stackexchange.com/questions/7258/how-do-i-prevent-vim-from-hiding-symbols-in-markdown-and-json

There are workarounds there that don't disable indentline, I think that setconceal=0 is disabling it.

Feel free to make a pull request once you find the best solution.
